### ISSUE TITLE
Move network methods out of build()

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#98] opened 2021-10-10 08:32 UTC
To prevent data reload when `build()` is repeatedly called, we must move network methods out of the function.

For every `StatefulWidget`, data load methods should be placed in `initState()`, and should only be called during `initState()` or **manual refresh**.

`build()` should only used the cached data loaded by `initState()`.

To determine whether `build()` contains networking methods, simply resize the app window (triggering a rebuild). If the data does not reload, then `build()` does not contain networking methods.

**Comment by w568w** [comment] 2021-12-06 06:42
We have done most of this work. Although there are still some network request methods in  `build()`, these `build()` will not be called so frequently to affect performance. 

**However, we should prevent to do so in the future - it is a bad practice.**

**Comment by singularity-s0** [comment] 2022-01-16 11:08
This was apparently not fixed, since resizing & changing theme still triggered data reload.

**Comment by singularity-s0** [comment] 2022-01-16 11:09
Maybe we could cache all data in repositories, and load via network only when cache is empty, or explicitly requested.

**Comment by w568w** [comment] 2022-01-16 11:37
It's wiser to generalize the logic of network requests. I will have some research, time permitted.

**Comment by w568w** [comment] 2022-02-19 02:28
> Exam grade page still reloads on rebuild.

See https://github.com/DanXi-Dev/DanXi/commit/d13a3a21266f58ff6331739718a9bb49171e5900

> Some methods in `empty_classroom_detail` and `exam_detail` are not moved out, because it makes the logic complex and cut down the readability.

I suppose it will not be fixed. Fix-it-yourself if necessary.

**Comment by w568w** [comment] 2022-06-30 07:50
Will this issue be dealt with? If not, I will mark it as stale and close it.

**Comment by singularity-s0** [comment] 2022-06-30 08:05
> Will this issue be dealt with? If not, I will mark it as stale and close it.

It is stale because people have other priorities, but that doesn't mean it should be closed.

**Comment by w568w** [comment] 2022-06-30 08:10
> > Will this issue be dealt with? If not, I will mark it as stale and close it.
> 
> It is stale because people have other priorities, but that doesn't mean it should be closed.

`Stale` is now a special case of closing issue in Github. 🤣 The icon implies that the issue is NOT completed yet, but not in future plans either.
![image](https://user-images.githubusercontent.com/8389787/176626755-9c81b808-6e3c-4094-88f0-fc59d4574bb3.png)

**Comment by singularity-s0** [comment] 2022-06-30 08:25
Fine, close it if you wish. Your last comment wasn't asking for any reply anyway.

**Comment by w568w** [comment] 2022-06-30 11:41
Close it since we have cleared most of network I/O out of rebuilding process.

**Closed by w568w** 2022-06-30 11:41 UTC
Labels: enhancement, good first issue
